name = "recipe-upload"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
ALLOWED_ORIGIN = "https://copyandpastry.com"
GITHUB_REPO = "lukelabonte/food-recipes"

[[kv_namespaces]]
binding = "KV"
id = "c3b5364e92a5498e824e96e7bd4adb4d"
